version: '3.8'

services:
  mysql:
    image: mysql
    container_name: 'base-nest'
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - mysql
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init-database.sql
      - ./docker/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: localhost
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: 1
    command: --default-authentication-plugin=mysql_native_password
networks:
  mysql:
    driver: bridge